export * from "./pentateuch/index.js";
export * from "./historical-books/index.js";
export * from "./wisdom-literature/index.js";
export * from "./major-prophets/index.js";
export * from "./minor-prophets/index.js";
export * from "./gospels/index.js";
export * from "./acts/index.js";
export * from "./pauline-epistles/index.js";
export * from "./general-epistles/index.js";