export enum ConnectingWordCategory {
    Addition = "Addition",
    Contrast = "Contrast",
    Comparison = "Comparison",
    Cause = "Cause",
    Result = "Result",
    Conclusion = "Conclusion",
    Condition = "Condition",
    Purpose = "Purpose",
    Explanation = "Explanation",
    Sequence = "Sequence",
    Time = "Time",
    Emphasis = "Emphasis",
    Example = "Example",
    Exception = "Exception",
    Clarification = "Clarification",
    Transition = "Transition",
    Means = "Means",
    Manner = "Manner",
    Location = "Location",
    Summary = "Summary",
}